env:
  global:
    CDN_BUCKET_NAME="eosio-eosjs"
sudo: false
language: node_js
node_js:
  - '10.0.0'    
before_install:
  - yarn global add typescript
  - yarn global add webpack 
before_script:
  - source ./scripts/is_latest.sh
script:
  - yarn run lint
  - yarn run test
  - yarn run build-web
deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - ./scripts/publish.sh
    on: 
      tags: true
      condition: $TRAVIS_IS_LATEST_TAG = true # sourced from ./scripts/is_latest.sh
  - provider: s3
    skip_cleanup: true
    access_key_id: $S3_USER_ID
    secret_access_key: $S3_USER_SECRET
    bucket: "${CDN_BUCKET_NAME}"
    region: us-west-2
    local_dir: dist-web
    upload-dir: $TRAVIS_TAG
    on: 
      tags: true
      condition: $TRAVIS_IS_LATEST_TAG = true # sourced from ./scripts/is_latest.sh
after_deploy:
  - echo "CDN base url - https://${CDN_BUCKET_NAME}.s3.amazonaws.com/${TRAVIS_TAG}/"